name: Dictation
options:
  bundleIdPrefix: jp.dictation.learning
  deploymentTarget:
    iOS: 17.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

targets:
  Dictation:
    type: application
    platform: iOS
    deploymentTarget: 17.0

    sources:
      - path: Dictation
        excludes:
          - Info.plist
          - Assets.xcassets

      - path: Dictation/Assets.xcassets
        buildPhase: resources

      - path: Assets
        buildPhase: resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: jp.dictation.learning
        PRODUCT_NAME: $(TARGET_NAME)
        INFOPLIST_FILE: Dictation/Info.plist
        DEVELOPMENT_TEAM: WS9392R3N8
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

schemes:
  Dictation:
    build:
      targets:
        Dictation: all
    run:
      config: Debug
      storeKitConfiguration: Dictation/Dictation.storekit
